### ISSUE TITLE
Emit player events

### ISSUE THREAD

**Issue by roderickvd** [roderickvd/pleezer#27]
### Feature Description

Currently, pleezer does not emit player events, though it's got the plumbing to do it. So question is: what would your ideal player event emitter look like?

- Should it call a script, or output to stdout?
- Which events would you like emitted?
- Which information would you like to have, per event?
- For recurring messages, what should the frequency be? (not event-based, maybe like playback progress)
- What should the script command look like (which command-line arguments, in which order)?
- Or, if to output to stdout: how should the messages be formatted?

### Implementation Ideas

I'm inclined to have only one method (script _or_ stdout). [I've asked the moOde guys](https://moodeaudio.org/forum/showthread.php?tid=7116), because what will work with them, should work for the rest.

### Due Diligence

- [X] I have searched the [issues](https://github.com/roderickvd/pleezer/issues) for similar feature requests
- [X] I have checked the documentation and confirmed that this feature is not already implemented
- [X] I have read and understood the [Contributing guidelines](https://github.com/roderickvd/pleezer/blob/main/CONTRIBUTING.md)

**Comment by moodeaudio** [comment]
The three renderers in moode that emit events are shairport-sync, librespot and squeezelight. They each provide options to specify a script to be called to process events. Shairport-sync options are in its conf file. Librespot and squeezelite use a command line option.

Of the three, librespot with its event environment variables and callable event handling script is the easiest to work with. 

For librespot we process three events: 
```
session_connected
session_disconnected
track_changed
```
For the `track_changed` event we use the env vars below to send metadata and cover art to the WebUI for display.
```
$NAME
$ARTISTS
$ALBUM
$DURATION_MS
$COVER
```

My preference would be to simply replicate the librespot style event system for pleezer starting with a basic set of events and some track metadata. Also has the benefit of reduced learning curve.

**Comment by roderickvd** [comment]
Hey Tim, thanks for your input!

> My preference would be to simply replicate the librespot style event system for pleezer starting with a basic set of events and some track metadata.

I went ahead and implemented that in https://github.com/roderickvd/pleezer/commit/8ce63740045a3d903ac771e2a4d18342d9839249. Compared to `librespot`, I renamed a couple of environment variables to be more succinct. I've documented them in the [README](https://github.com/roderickvd/pleezer/tree/main?tab=readme-ov-file#hook-scripts).

There's a lot more I could output. Let me know when you've got any requests.

**Comment by moodeaudio** [comment]
Nice :-)

Is track metadata and cover url available via their API?

**Comment by roderickvd** [comment]
Yes:

https://github.com/roderickvd/pleezer/blob/64936e01b7705fb241e6dc394f3ecba0ab453088/README.md?plain=1#L235-L250

There's more if you need.

**Comment by roderickvd** [comment]
Closing as completed. Don't hesitate to open a new one if you'd like more or different metadata.
