### ISSUE TITLE
Deb build friendly by adding metadata deb to Cargo.toml

### ISSUE THREAD

**Issue by bitkeeper** [roderickvd/pleezer#29]
### Feature Description

For moOde we build and deploy every piece of software as deb package.
For `rust` based software we use `cargo-deb` to create the deb and patch the meta data deb to teh Cargo.toml.

It would be nice it pleezer (like librespot) has an already present section `[package.metadata.deb]` in the `Cargo.yml`. In this ways package has always the correct metadata as maintainer provide it.

### Due Diligence

- [X] I have searched the [issues](https://github.com/roderickvd/pleezer/issues) for similar feature requests
- [X] I have checked the documentation and confirmed that this feature is not already implemented
- [X] I have read and understood the [Contributing guidelines](https://github.com/roderickvd/pleezer/blob/main/CONTRIBUTING.md)

**Comment by roderickvd** [comment]
Sure! Please review what I've added in #30.

**Comment by bitkeeper** [comment]
Greate PR #30 does do the job.
