### ISSUE TITLE
Track progress not increasing

### ISSUE THREAD

**Issue by denys-lysiuk** [roderickvd/pleezer#38]
### Bug Description

When playing an album, starting from the third track in the queue track progress is not increasing, resetting to 00:00 constantly. Was able to reproduce it on different albums on both iPhone and iPad. `Send` log chunks contain `progress: Some(Percentage(0.0,),)` in such cases. Does not affect playback itself, only visual representation in Deezer app.

### Steps to Reproduce

1. Launch the player, play an album.
2. Starting from track №3 in the queue playback progress is being displayed only from 00:00 to 00:02 and then resets.

### Logs

```shell
# WHEN NO ISSUE:

[2024-11-28T12:45:07Z TRACE pleezer::remote] Send {
        channel: Channel {
            from: Id(
                6258794423,
            ),
            to: Id(
                6258794423,
            ),
            ident: RemoteCommand,
        },
        contents: Contents {
            ident: RemoteCommand,
            headers: Headers {
                from: Uuid(
                    02b65b79-f09d-5686-ae9a-e26874337ba2,
                ),
                destination: Some(
                    Other(
                        "y1b1b9e162a6a6b6f0454e119f84d6265",
                    ),
                ),
            },
            body: PlaybackProgress {
                message_id: "64c6d8e1-380c-4413-a781-7083c026d453",
                track: QueueItem {
                    queue_id: "FC1634A3-DF7C-4894-9057-6113E5A65067",
                    track_id: 2957670541,
                    position: 1,
                },
                quality: Lossless,
                duration: 276s,
                buffered: 276s,
                progress: Some(
                    Percentage(
                        0.9785270094871521,
                    ),
                ),
                volume: Percentage(
                    1.0,
                ),
                is_playing: true,
                is_shuffle: false,
                repeat_mode: None,
            },
        },
    }


# DURING THE ISSUE:

[2024-11-28T12:49:34Z TRACE pleezer::remote] Send {
        channel: Channel {
            from: Id(
                6258794423,
            ),
            to: Id(
                6258794423,
            ),
            ident: RemoteCommand,
        },
        contents: Contents {
            ident: RemoteCommand,
            headers: Headers {
                from: Uuid(
                    02b65b79-f09d-5686-ae9a-e26874337ba2,
                ),
                destination: Some(
                    Other(
                        "y1b1b9e162a6a6b6f0454e119f84d6265",
                    ),
                ),
            },
            body: PlaybackProgress {
                message_id: "432176ae-12b7-454c-97b5-a0aceaadd571",
                track: QueueItem {
                    queue_id: "FC1634A3-DF7C-4894-9057-6113E5A65067",
                    track_id: 2957670551,
                    position: 2,
                },
                quality: Lossless,
                duration: 331s,
                buffered: 331s,
                progress: Some(
                    Percentage(
                        0.0,
                    ),
                ),
                volume: Percentage(
                    1.0,
                ),
                is_playing: true,
                is_shuffle: false,
                repeat_mode: None,
            },
        },
    }
```

### Operating System

Raspberry Pi OS 12

### pleezer version

Latest from `fix/parse-user-token` branch

### Rust version (if building from source)

1.82.0

### Hardware specifications

Raspberry Pi 5 4GB

### Deezer client specifications

Deezer 10.25.1.1, iPadOS 18.1.1, iOS 18.1.1

### Due Diligence

- [X] I am using the [latest version](https://github.com/roderickvd/pleezer/releases) of pleezer
- [X] I have searched the [issues](https://github.com/roderickvd/pleezer/issues) for similar reports
- [X] I have included a full verbose log from launch to the issue, not just an excerpt
- [X] I confirm that this is an issue with pleezer, not with my system configuration or other software
- [X] I confirm that this is not a security issue, which should be [reported](https://github.com/roderickvd/pleezer/security/policy) privately
- [X] I have read and understood the [Contributing guidelines](https://github.com/roderickvd/pleezer/blob/main/CONTRIBUTING.md)

**Comment by roderickvd** [comment]
Hi Denys, indeed I've seen this happen on some occasions as well. Is it reproducible for you on *every* third track of an album?

It would really help me if you could give me a completely reproducible case.

**Comment by denys-lysiuk** [comment]
> Is it reproducible for you on _every_ third track of an album?

Yeah, that seems to be the case - I've tried like 4 albums atm. And I'm seeing it on all album tracks starting from third onwards.

**Comment by denys-lysiuk** [comment]
Skipping to the next track exhibits the same behavior - two next tracks display progress correctly, starting from the third - the issue is back.

**Comment by roderickvd** [comment]
Should be fixed in https://github.com/roderickvd/pleezer/commit/b53b951293bf0ac4a8f92bd239fa5df8d684d0c8, please reopen if it's not the case.

Keep 'em coming! 🚀
